### ISSUE TITLE
Everything is installed correctly but can't use the lib? 

### ISSUE THREAD

**Issue by ghost** [mscdex/sipster#24]
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libresample.so.2: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/alex/node_modules/sipster/lib/main.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[nodemon] app crashed - waiting for file chan

**Comment by mscdex** [comment]
It seems like the pjsip libraries are not in your library search path? If you search for that file, is it in /usr/local/lib? If so, do you have an entry in /etc/ld.so.conf.d that contains /usr/local/lib?
