### ISSUE TITLE
Problems installing sipster

### ISSUE THREAD

**Issue by fdl33333** [mscdex/sipster#35]
root@raspberrypi:~# node -v
v11.15.0
root@raspberrypi:~# p
-bash: p: command not found
root@raspberrypi:~# npm -v
6.7.0
root@raspberrypi:~# pkg-config -version
Unknown option -version
root@raspberrypi:~# pkg-config --version
0.29

"npm install sipster" gives:

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.42-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/sipster
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by surrsoft** [comment]
analogue `npm ERR! sipster@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sipster@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`
